### PR TITLE
Add Cerner authentication

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**
This PR adds authentication for Cerner

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Yeah, you shouldn't need to depend on FHIRClient here.

**Comment by Vaibhavdixit02** [comment]
yes @DilumAluthge , the second commit removed the dependency

**Comment by Vaibhavdixit02** [comment]
@DilumAluthge I believe the way to run the test might be register a dummy app and use that? I made an attempt for it and it wasn't successful, I think we should discuss this on the call tomorrow and use that to wrap this PR up with the test added

**Review by DilumAluthge — COMMENTED** [review]
I'm going to merge this as-is, and then I'll make a follow-up PR with some style nits and other changes.

**Pull request merged**
